'use client'
import { useState } from 'react';
import { useRouter } from 'next/navigation'; // 引入 useRouter
import Image from 'next/image';
// css
import "@styles/helper-class.scss";
// 套件
import { ConfigProvider, Layout, Menu } from 'antd';
import 'antd/dist/reset.css';
import '@styles/layout.scss';
import { AppstoreOutlined, MailOutlined, SettingOutlined } from '@ant-design/icons';
import PerfectScrollbar from 'react-perfect-scrollbar';
import 'react-perfect-scrollbar/dist/css/styles.css';

const { Header, Sider, Content } = Layout;

// import { AntdRegistry } from '@ant-design/nextjs-registry';
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const items = [
  {
    key: 'sub0',
    label: 'README',
    icon: <MailOutlined />,
    // children: [
    // { key: '1', label: 'Option 1' },
    // { key: '2', label: 'Option 2' },
    // { key: '3', label: 'Option 3' },
    // { key: '4', label: 'Option 4' },
    // ],
  },
  {
    key: 'sub1',
    label: 'HTML',
    icon: <MailOutlined />,
    children: [
      { key: '1', label: 'Option 1' },
      { key: '2', label: 'Option 2' },
      { key: '3', label: 'Option 3' },
      { key: '4', label: 'Option 4' },
    ],
  },
  {
    key: 'sub2',
    label: 'CSS',
    icon: <AppstoreOutlined />,
    children: [
      { key: '101', label: 'Option 5' },
      { key: '102', label: 'Option 6' },
      // {
      //   key: 'sub3',
      //   label: 'Submenu',
      //   children: [
      //     { key: '7', label: 'Option 7' },
      //     { key: '8', label: 'Option 8' },
      //   ],
      // },
    ],
  },
  {
    key: 'sub4',
    label: 'Javascript',
    icon: <SettingOutlined />,
    children: [
      { key: '201', label: 'Option 9' },
      { key: '202', label: 'Option 10' },
      { key: '203', label: 'Option 11' },
      { key: '204', label: 'Option 12' },
    ]
  },
  {
    key: 'sub5',
    label: 'React',
    icon: <SettingOutlined />,
    children: [
      { key: '301', label: 'Option 9' },
      { key: '302', label: 'Option 10' },
      { key: '303', label: 'Option 11' },
      { key: '304', label: 'Option 12' },
    ],
  },
  {
    key: 'sub6',
    label: 'Database',
    icon: <SettingOutlined />,
    children: [
      { key: '401', label: 'Option 9' },
      { key: '402', label: 'Option 10' },
      { key: '403', label: 'Option 11' },
      { key: '404', label: 'Option 12' },
    ],
  },
  {
    key: 'sub7',
    label: 'Browser',
    icon: <SettingOutlined />,
    children: [
      { key: '501', label: 'Option 9' },
      { key: '502', label: 'Option 10' },
      { key: '503', label: 'Option 11' },
      { key: '504', label: 'Option 12' },
    ],
  },
  {
    key: 'sub8',
    label: '前端架構設計',
    icon: <SettingOutlined />,
    children: [
      { key: '601', label: 'Option 9' },
      { key: '602', label: 'Option 10' },
      { key: '603', label: 'Option 11' },
      { key: '604', label: 'Option 12' },
    ],
  },
  {
    key: 'sub9',
    label: '前端架構設計',
    icon: <SettingOutlined />,
    children: [
      { key: '701', label: 'Option 9' },
      { key: '702', label: 'Option 10' },
      { key: '703', label: 'Option 11' },
      { key: '704', label: 'Option 12' },
    ],
  },
  {
    key: 'sub10',
    label: '前端工具',
    icon: <SettingOutlined />,
    children: [
      { key: '801', label: 'Option 9' },
      { key: '802', label: 'Option 10' },
      { key: '803', label: 'Option 11' },
      { key: '804', label: 'Option 12' },
    ],
  },
  {
    key: 'sub11',
    label: '網路安全',
    icon: <SettingOutlined />,
    children: [
      { key: '901', label: 'Option 9' },
      { key: '902', label: 'Option 10' },
      { key: '903', label: 'Option 11' },
      { key: '904', label: 'Option 12' },
    ],
  },
  {
    key: 'sub12',
    label: '效能優化',
    icon: <SettingOutlined />,
    children: [
      { key: '1001', label: 'Option 9' },
      { key: '1002', label: 'Option 10' },
      { key: '1003', label: 'Option 11' },
      { key: '1004', label: 'Option 12' },
    ],
  },
];
export default function RootLayout({ children }) {
  // ===================  variables  ===================
  const [theme, setTheme] = useState('light');
  const [current, setCurrent] = useState('1');

  const router = useRouter();
  // ===================  functions  ===================
  // 查找 label 的輔助函數
  const findLabelByKey = (key) => {
    for (const item of items) {
      if (item.key === key) return item.label;
      if (item.children) {
        const child = item.children.find((child) => child.key === key);
        if (child) return child.label;
      }
    }
    return null;
  };
  // 改變 亮暗主題
  const changeTheme = value => {
    setTheme(value ? 'dark' : 'light');
  };
  const menuClick = e => {
    // console.log('click ', e.key);
    setCurrent(e.key);

    // console.log(e)
    const label = findLabelByKey(e.key); // 根據 key 找到 label
    if (label && typeof label === 'string') {
      const cleanLabel = label.replace(/\s+/g, '').toLowerCase();
      if (cleanLabel) {
        router.push(`/articles/${cleanLabel}`); // 改為 /articles/xxxx
      } else {
        console.error('Clean label is empty for key:', e.key);
      }
    } else {
      console.error('Label not found or invalid for key:', e.key);
    }
  };
  return (
    <html lang="en">
      <body className={``}>
        <ConfigProvider
          theme={{
            token: { colorPrimary: '#1890ff', borderRadius: 4 },
            components: {
              Menu: {
                // colorBgBase: '#242424', // 背景色
                // colorText: '#your-text-color', // 文字色
                colorPrimary: '#4D648D', // 高亮色
                // itemHoverBg: '#your-hover-bg', // 懸停背景色
                itemSelectedBg: '#D0E1F9', // 選中背景色
                itemActiveBg: '#e6effd', // 點擊瞬間的背景色
              },
            },
          }}

        >
          <div className="Header useBetween">
            <Image
              src="/logo.png"
              alt="logo"
              width="52"
              height="40"
            />
          </div>
          <div className="useStart layout-2">
            <PerfectScrollbar className="Sidebar">
              <Menu
                theme={theme}
                onClick={menuClick}
                style={{ width: '100%' }}
                defaultOpenKeys={['sub1']}
                selectedKeys={[current]}
                mode="inline"
                items={items}
              />
            </PerfectScrollbar>
            <div className="Main">{children}</div>
          </div>
        </ConfigProvider>
      </body>
    </html>
  );
}
