'use client'
// import "./globals.css";
import 'antd/dist/reset.css';
import '@styles/layout.scss';
import "@styles/helper-class.scss";

// import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider, Layout } from 'antd';

const { Header, Sider, Content } = Layout;

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
          <ConfigProvider theme={{ token: { colorPrimary: '#1890ff', borderRadius: 4 } }}>
            <div className="Header">header</div>
            <div className="useStart bd layout-2">
              <div className="Sidebar bd">Sidebar</div>
              <div className="Main">{children}</div>
            </div>
          </ConfigProvider>
      </body>
    </html>
  );
}
