'use client'
// import "./globals.css";
import { useState } from 'react';
import 'antd/dist/reset.css';
import '@styles/layout.scss';
import "@styles/helper-class.scss";
// import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider, Layout, Menu } from 'antd';
import { AppstoreOutlined, MailOutlined, SettingOutlined } from '@ant-design/icons';

import PerfectScrollbar from 'react-perfect-scrollbar';
import 'react-perfect-scrollbar/dist/css/styles.css';


const { Header, Sider, Content } = Layout;

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const items = [
  {
    key: 'sub0',
    label: 'README',
    icon: <MailOutlined />,
    // children: [
      // { key: '1', label: 'Option 1' },
      // { key: '2', label: 'Option 2' },
      // { key: '3', label: 'Option 3' },
      // { key: '4', label: 'Option 4' },
    // ],
  },
  {
    key: 'sub1',
    label: 'HTML',
    icon: <MailOutlined />,
    children: [
      { key: '1', label: 'Option 1' },
      { key: '2', label: 'Option 2' },
      { key: '3', label: 'Option 3' },
      { key: '4', label: 'Option 4' },
    ],
  },
  {
    key: 'sub2',
    label: 'CSS',
    icon: <AppstoreOutlined />,
    children: [
      { key: '101', label: 'Option 5' },
      { key: '102', label: 'Option 6' },
      // {
      //   key: 'sub3',
      //   label: 'Submenu',
      //   children: [
      //     { key: '7', label: 'Option 7' },
      //     { key: '8', label: 'Option 8' },
      //   ],
      // },
    ],
  },
  {
    key: 'sub4',
    label: 'Javascript',
    icon: <SettingOutlined />,
    children: [
      { key: '201', label: 'Option 9' },
      { key: '202', label: 'Option 10' },
      { key: '203', label: 'Option 11' },
      { key: '204', label: 'Option 12' },
    ]
  },
  {
    key: 'sub5',
    label: 'React',
    icon: <SettingOutlined />,
    children: [
      { key: '301', label: 'Option 9' },
      { key: '302', label: 'Option 10' },
      { key: '303', label: 'Option 11' },
      { key: '304', label: 'Option 12' },
    ],
  },
  {
    key: 'sub6',
    label: 'Database',
    icon: <SettingOutlined />,
    children: [
      { key: '401', label: 'Option 9' },
      { key: '402', label: 'Option 10' },
      { key: '403', label: 'Option 11' },
      { key: '404', label: 'Option 12' },
    ],
  },
  {
    key: 'sub7',
    label: 'Browser',
    icon: <SettingOutlined />,
    children: [
      { key: '501', label: 'Option 9' },
      { key: '502', label: 'Option 10' },
      { key: '503', label: 'Option 11' },
      { key: '504', label: 'Option 12' },
    ],
  },
  {
    key: 'sub8',
    label: '前端架構設計',
    icon: <SettingOutlined />,
    children: [
      { key: '601', label: 'Option 9' },
      { key: '602', label: 'Option 10' },
      { key: '603', label: 'Option 11' },
      { key: '604', label: 'Option 12' },
    ],
  },
  {
    key: 'sub9',
    label: '前端架構設計',
    icon: <SettingOutlined />,
    children: [
      { key: '701', label: 'Option 9' },
      { key: '702', label: 'Option 10' },
      { key: '703', label: 'Option 11' },
      { key: '704', label: 'Option 12' },
    ],
  },
  {
    key: 'sub10',
    label: '前端工具',
    icon: <SettingOutlined />,
    children: [
      { key: '801', label: 'Option 9' },
      { key: '802', label: 'Option 10' },
      { key: '803', label: 'Option 11' },
      { key: '804', label: 'Option 12' },
    ],
  },
  {
    key: 'sub11',
    label: '網路安全',
    icon: <SettingOutlined />,
    children: [
      { key: '901', label: 'Option 9' },
      { key: '902', label: 'Option 10' },
      { key: '903', label: 'Option 11' },
      { key: '904', label: 'Option 12' },
    ],
  },
  {
    key: 'sub12',
    label: '效能優化',
    icon: <SettingOutlined />,
    children: [
      { key: '1001', label: 'Option 9' },
      { key: '1002', label: 'Option 10' },
      { key: '1003', label: 'Option 11' },
      { key: '1004', label: 'Option 12' },
    ],
  },
];
export default function RootLayout({ children }) {
  const [theme, setTheme] = useState('light');

  const [current, setCurrent] = useState('1');
  const changeTheme = value => {
    setTheme(value ? 'dark' : 'light');
  };
  const onClick = e => {
    console.log('click ', e);
    setCurrent(e.key);
  };
  return (
    <html lang="en">
      <body className={``}>
          <ConfigProvider theme={{ token: { colorPrimary: '#1890ff', borderRadius: 4 } }}>
            <div className="Header">header</div>
            <div className="useStart bd layout-2">
              <PerfectScrollbar className="Sidebar">
                <Menu
                  
                  theme={theme}
                  onClick={onClick}
                  style={{ width: '100%' }}
                  defaultOpenKeys={['sub1']}
                  selectedKeys={[current]}
                  mode="inline"
                  items={items}
                />
              </PerfectScrollbar>
              <div className="Main">{children}</div>
            </div>
          </ConfigProvider>
      </body>
    </html>
  );
}
